language: android
jdk:
  - oraclejdk8
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16

before_install:
- nvm install 6
- node --version
- curl -L  https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
- chmod a+x lein
- sudo mv lein /bin

install:
- npm install
script:
- lein prod-build
- cd android && ./gradlew assembleRelease
