language: objective-c

osx_image: xcode8.3

xcode_project: ios/MobilePatient.xcodeproj # path to your xcodeproj folder
xcode_scheme: Release

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/google-cloud-sdk/
    - $HOME/.m2
    - /home/travis/build/Aidbox/mobile-patient/node_modules


before_install:
#  - brew update
#  - brew install node
  - brew install watchman
  - npm install -g react-native-cli
  - curl -L  https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
  - chmod a+x lein

script:
  - ./lein do clean, with-profile -dev,+prod,+patient cljsbuild once || travis_terminate 1
  - react-native run-ios --configuration Release
