language: android
jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.m2
    - /home/travis/build/Aidbox/mobile-patient/node_modules

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16

env:
  global:
    - GC_SA=mobile@aidbox-next.iam.gserviceaccount.com
    - BUCKET=gs://aidbox-mobile-patient

before_install:
  - nvm install 6
  - npm install
  - curl -L  https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
  - chmod a+x lein && sudo mv lein /bin
  - openssl aes-256-cbc -K $encrypted_df8305bdbb16_key -iv $encrypted_df8305bdbb16_iv -in account.json.enc -out account.json -d
  - wget https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash
  - chmod +x install_google_cloud_sdk.bash
  - ./install_google_cloud_sdk.bash --disable-prompts --install-dir=$HOME
  - export PATH=$PATH:$HOME/google-cloud-sdk/bin
  - gcloud auth activate-service-account $GC_SA --key-file=account.json

script:
  - lein prod-build
  - cd android && ./gradlew assembleRelease && cd ..
  - gsutil cp -r ./android/app/build/outputs/apk/app-release-unsigned.apk $BUCKET/mobile-patient/$TRAVIS_COMMIT/app.apk
  - gsutil acl -r ch -u AllUsers:R $BUCKET
  - echo "https://storage.googleapis.com/aidbox-mobile-patient/mobile-patient/$TRAVIS_COMMIT/app.apk"

