language: android
jdk:
  - oraclejdk8
before_install:
- sudo add-apt-repository ppa:mikegedelman/leiningen-git-stable
- sudo apt-get update -q
- sudo apt-get install leiningen -y
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- lein prod-build
- cd android && ./gradlew assembleRelease
